ctf/urls.py
from django.urls import path

from . import views

app_name = 'ctf'
urlpatterns = [
    path('', views.index, name="index"),
    path('information/', views.information, name="information"),
    path('ranking/', views.ranking, name="ranking"),
    path('problem_list/', views.problem_list, name="problem_list"),
    path('board/', views.board, name="board"),
    path('inquiry/', views.inquiry, name="inquiry"),
    path('my_page/', views.my_page, name="my_page"),
    path('status/<int:pk>/', views.status, name="status"),
    path('account_delete/', views.account_delete, name="account_delete"),
    path('problem_detail/<int:pk>/', views.problem_detail, name="problem_detail"),
]

ctf/models.py
from django.contrib.auth import get_user_model
from django.core.validators import RegexValidator
from django.db import models


class Problem(models.Model):
    """問題モデル"""

    class Meta:
        db_table = 'problem'
        verbose_name = verbose_name_plural = '問題'

    answer_regex = RegexValidator(regex=r'^ctf\{[\w]+\}$', message='正しい入力方式で入力してください。')

    GENRE = (
        ('crypto', 'Crypto'),
        ('forensics', 'Forensics'),
        ('reversing', 'Reversing'),
        ('pwnable', 'Pwnable'),
        ('web', 'Web'),
        ('network', 'Network'),
        ('misc', 'Misc'),
    )

    LEVEL = (
        (0, 0),
        (1, 1),
        (2, 2),
        (3, 3),
        (4, 4),
        (5, 5),
    )

    name = models.CharField(verbose_name='問題名', max_length=50)
    file = models.FileField(verbose_name='問題ファイル', upload_to='problems/', null=True, blank=True)
    statement = models.TextField(verbose_name='問題文')
    genre = models.CharField(verbose_name='問題ジャンル', choices=GENRE, max_length=50)
    level = models.IntegerField(verbose_name='問題難易度', choices=LEVEL)
    score = models.IntegerField(verbose_name='問題得点')
    answer = models.CharField(verbose_name='問題解答', validators=[answer_regex], max_length=50)
    created_at = models.DateTimeField(verbose_name='問題作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='問題更新日時', auto_now=True)

    # UserProblemテーブルとPersonテーブルの間にUserProblem中間テーブル
    custom_user = models.ManyToManyField(get_user_model(), through='UserProblem')

    def __str__(self):
        return self.name


class UserProblem(models.Model):
    """ユーザ問題モデル（中間テーブル）"""

    class Meta:
        db_table = 'user_problem'
        verbose_name = verbose_name_plural = 'ユーザ問題'
        unique_together = ['custom_user', 'problem']

    # リレーション
    custom_user = models.ForeignKey(get_user_model(), verbose_name='ユーザ名', on_delete=models.CASCADE)
    problem = models.ForeignKey(Problem, verbose_name='問題名', on_delete=models.CASCADE)

    problem_correct_answer = models.BooleanField(verbose_name='問題正解', default=0)
    corrected_at = models.DateTimeField(verbose_name='問題正解日時', null=True, blank=True)


class Information(models.Model):
    """お知らせモデル"""

    class Meta:
        db_table = 'information'
        verbose_name = verbose_name_plural = 'お知らせ'

    title = models.CharField(verbose_name='お知らせタイトル', max_length=50)
    contents = models.TextField(verbose_name='お知らせ内容')
    created_at = models.DateTimeField(verbose_name='お知らせ作成日時', auto_now_add=True)
    updated_at = models.DateTimeField(verbose_name='お知らせ更新日時', auto_now=True)

    def __str__(self):
        return self.title


class Inquiry(models.Model):
    """お問い合わせモデル"""

    class Meta:
        db_table = 'inquiry'
        verbose_name = verbose_name_plural = 'お問い合わせ'

    name = models.CharField(verbose_name='名前', max_length=50)
    email = models.EmailField(verbose_name='メールアドレス')
    subject = models.CharField(verbose_name='お問い合わせ件名', max_length=50)
    contents = models.TextField(verbose_name='お問い合わせ内容')
    created_at = models.DateTimeField(verbose_name='お問い合わせ日時', auto_now_add=True)

    def __str__(self):
        return self.subject

ctf/forms.py
from django.core.mail import EmailMessage
from django.forms import ImageField

from .models import Problem, Inquiry
from django import forms
from django.contrib.auth import get_user_model

User = get_user_model()


class ProblemDetailForm(forms.ModelForm):
    """問題詳細フォーム"""

    class Meta:
        model = Problem
        fields = ('answer',)
        labels = {
            'name': '名前',
            'email': 'メールアドレス',
            'subject': '件名',
            'contents': '内容',
        }

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['answer'].widget.attrs = {'placeholder': 'ctf{sample_answer}',
                                              'class': 'form-control'}


class InquiryForm(forms.ModelForm):
    """お問い合わせフォーム"""

    class Meta:
        model = Inquiry
        fields = ('name', 'email', 'subject', 'contents')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['name'].widget.attrs = {'placeholder': 'お名前を入力してください。', }
        self.fields['email'].widget.attrs = {'placeholder': 'メールアドレスを入力してください。'}
        self.fields['subject'].widget.attrs = {'placeholder': '件名を入力してください。'}
        self.fields['contents'].widget.attrs = {'placeholder': 'お問い合わせ内容を入力してください。',
                                                'rows': 10}
        for field in self.fields.values():
            field.widget.attrs['class'] = 'form-control'

    def send_email(self):
        name = self.cleaned_data['name']
        email = self.cleaned_data['email']
        subject = self.cleaned_data['subject']
        contents = self.cleaned_data['contents']

        message = '送信者名: {0}\nメールアドレス: {1}\n内容:\n{2}'.format(name, email, contents)
        from_email = 'beginnersctf@gmail.com'
        to_list = [
            'yoshida.mitsuki1203@gmail.com'
        ]

        message = EmailMessage(subject=subject, body=message, from_email=from_email, to=to_list)
        message.send()


class MyPageForm(forms.ModelForm):
    """マイページフォーム"""
    username = forms.CharField(label='ユーザ名', max_length=30)

    class Meta:
        model = User
        fields = ('icon', 'username',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        for field in self.fields.values():
            field.widget.attrs['class'] = "form-control"


class AccountDeleteForm(forms.ModelForm):
    """アカウント削除フォーム"""

    class Meta:
        model = User
        fields = ('email',)

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['email'].widget.attrs = {'placeholder': 'メールアドレス', }
        for field in self.fields.values():
            field.widget.attrs['class'] = "form-control"

ctf/views.py
import datetime
import logging

import django_tables2
from django.http import HttpResponseRedirect
from django.template.response import TemplateResponse
from django.urls import reverse_lazy, reverse
from django.utils.html import escape
from django.utils.safestring import mark_safe
from django_tables2 import tables, RequestConfig

from .forms import ProblemDetailForm, InquiryForm, MyPageForm, AccountDeleteForm
from .models import Information, Problem, UserProblem
from django.contrib.auth import get_user_model
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views import View
from django.views.generic import TemplateView, ListView, DetailView, FormView, UpdateView, DeleteView
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages

User = get_user_model()

logger = logging.getLogger(__name__)


class IndexView(TemplateView):
    """indexページ"""

    template_name = 'ctf/index.html'


index = IndexView.as_view()


class InformationListView(ListView):
    """お知らせページ"""

    model = Information
    template_name = 'ctf/information.html'

    def get_queryset(self):
        return Information.objects.order_by('-created_at')


information = InformationListView.as_view()


class ImageColumn(django_tables2.Column):
    """アイコンのフォーマット"""

    def render(self, value):
        return mark_safe(
            '<img src="/media/%s" class="rounded-circle border me-1" width="40" height="40" alt="" loading="lazy" />'
            % (escape(value),))


class RankingTable(tables.Table):
    """ユーザテーブルのランキング表示"""

    icon = ImageColumn('アイコン')

    class Meta:
        model = User
        fields = ('ranking', 'icon', 'username', 'score')


class RankingView(LoginRequiredMixin, View):
    """ランキングページ"""

    def get(self, request, *args, **kwargs):
        queryset = User.objects.order_by('ranking')
        # テーブルオブジェクトを作成
        table = RankingTable(queryset)
        RequestConfig(request).configure(table)
        table.paginate(page=request.GET.get('page', 1), per_page=100)
        context = {
            'table': table,
        }
        return TemplateResponse(request, 'ctf/ranking.html', context)


ranking = RankingView.as_view()


class ProblemListView(LoginRequiredMixin, ListView):
    """問題一覧ページ"""

    model = UserProblem
    template_name = 'ctf/problem_list.html'

    def get_queryset(self):
        return UserProblem.objects.all().select_related('problem').filter(
            custom_user_id=self.request.user.id, ).order_by('problem_id__level')


problem_list = ProblemListView.as_view()


class BoardView(LoginRequiredMixin, TemplateView):
    """掲示板ページ"""

    template_name = 'ctf/board.html'


board = BoardView.as_view()


class InquiryView(FormView):
    template_name = 'ctf/inquiry.html'
    form_class = InquiryForm
    success_url = reverse_lazy('ctf:inquiry')

    def form_valid(self, form):
        form.send_email()
        messages.success(self.request, 'メッセージを送信しました。')
        # ロギング
        logger.info('Inquiry sent by {}'.format(form.cleaned_data['name']))
        # モデルに登録
        form.save()
        return super().form_valid(form)


inquiry = InquiryView.as_view()


class MyPageView(LoginRequiredMixin, View):
    """マイページ"""

    def get(self, request, *args, **kwargs):
        queryset = User.objects.get(id=request.user.id)
        initial_data = {
            'icon': queryset.icon,
            'username': queryset.username,
        }
        context = {}
        form = MyPageForm(initial=initial_data)
        context["form"] = form
        return render(request, 'ctf/my_page.html', context)

    def post(self, request, *args, **kwargs):
        context = {}
        # instanceでログイン中のユーザ情報をformsに返す
        form = MyPageForm(request.POST, request.FILES)

        if form.is_valid():
            icon = form.cleaned_data["icon"]
            username = form.cleaned_data["username"]

            # モデル変更
            user = User.objects.get(username=request.user.username)
            # ファイルを選択しない時はアイコンは変更しない
            if icon != 'icon/default.jpg':
                user.icon = icon
            user.username = username
            user.save()

            # メッセージ
            messages.info(request, "ユーザー情報を変更しました。")

            return redirect('ctf:my_page')

        else:
            # バリデーションチェックに引っかかった場合はアイコンのみ更新するか判断
            icon = form.cleaned_data["icon"]

            # ファイルを選択しない時はアイコンは変更しない
            if icon != 'icon/default.jpg':
                # モデル変更
                user = User.objects.get(username=request.user.username)
                user.icon = icon
                user.save()

                # メッセージ
                messages.info(request, "ユーザー情報を変更しました。")
                return redirect('ctf:my_page')
            else:
                context["form"] = form
                return render(request, 'ctf/my_page.html', context)


my_page = MyPageView.as_view()


class StatusView(LoginRequiredMixin, View):
    """ステータスページ"""

    model = User
    template_name = 'ctf/status.html'

    def get(self, request, *args, **kwargs):
        user_pk = get_object_or_404(User, pk=self.kwargs['pk'])

        # ALL
        all_count = User.objects.all().prefetch_related('userproblem').filter(
            userproblem__custom_user_id=self.request.user.id
        ).count()

        solved_all_count = User.objects.all().prefetch_related('userproblem').filter(
            userproblem__custom_user_id=self.request.user.id,
            userproblem__problem_correct_answer=True
        ).count()

        try:
            all_per = round((solved_all_count / all_count) * 100)
        except ZeroDivisionError:
            all_per = 0

        # Crypto
        crypto_count = User.objects.all().prefetch_related('userproblem').select_related(
            'problem').filter(
            userproblem__custom_user_id=self.request.user.id,
            problem__genre='crypto'
        ).count()

        solved_crypto_count = get_user_model().objects.all().prefetch_related('userproblem').select_related(
            'problem').filter(
            userproblem__custom_user_id=self.request.user.id,
            userproblem__problem_correct_answer=True,
            problem__genre='crypto'
        ).count()

        try:
            crypto_per = round((solved_crypto_count / crypto_count) * 100)
        except ZeroDivisionError:
            crypto_per = 0

        # Forensics
        forensics_count = User.objects.all().prefetch_related('userproblem').select_related(
            'problem').filter(
            userproblem__custom_user_id=self.request.user.id,
            problem__genre='forensics'
        ).count()

        solved_forensics_count = get_user_model().objects.all().prefetch_related('userproblem').select_related(
            'problem').filter(
            userproblem__custom_user_id=self.request.user.id,
            userproblem__problem_correct_answer=True,
            problem__genre='forensics'
        ).count()

        try:
            forensics_per = round((solved_forensics_count / forensics_count) * 100)
        except ZeroDivisionError:
            forensics_per = 0

        # Reversing
        reversing_count = User.objects.all().prefetch_related('userproblem').select_related(
            'problem').filter(
            userproblem__custom_user_id=self.request.user.id,
            problem__genre='reversing'
        ).count()

        solved_reversing_count = get_user_model().objects.all().prefetch_related('userproblem').select_related(
            'problem').filter(
            userproblem__custom_user_id=self.request.user.id,
            userproblem__problem_correct_answer=True,
            problem__genre='reversing'
        ).count()

        try:
            reversing_per = round((solved_reversing_count / reversing_count) * 100)
        except ZeroDivisionError:
            reversing_per = 0

        # Pwnable
        pwnable_count = User.objects.all().prefetch_related('userproblem').select_related(
            'problem').filter(
            userproblem__custom_user_id=self.request.user.id,
            problem__genre='pwnable'
        ).count()

        solved_pwnable_count = get_user_model().objects.all().prefetch_related('userproblem').select_related(
            'problem').filter(
            userproblem__custom_user_id=self.request.user.id,
            userproblem__problem_correct_answer=True,
            problem__genre='pwnable'
        ).count()

        try:
            pwnable_per = round((solved_pwnable_count / pwnable_count) * 100)
        except ZeroDivisionError:
            pwnable_per = 0

        # Web
        web_count = User.objects.all().prefetch_related('userproblem').select_related(
            'problem').filter(
            userproblem__custom_user_id=self.request.user.id,
            problem__genre='web'
        ).count()

        solved_web_count = get_user_model().objects.all().prefetch_related('userproblem').select_related(
            'problem').filter(
            userproblem__custom_user_id=self.request.user.id,
            userproblem__problem_correct_answer=True,
            problem__genre='web'
        ).count()

        try:
            web_per = round((solved_web_count / web_count) * 100)
        except ZeroDivisionError:
            web_per = 0

        # Network
        network_count = User.objects.all().prefetch_related('userproblem').select_related(
            'problem').filter(
            userproblem__custom_user_id=self.request.user.id,
            problem__genre='network'
        ).count()

        solved_network_count = get_user_model().objects.all().prefetch_related('userproblem').select_related(
            'problem').filter(
            userproblem__custom_user_id=self.request.user.id,
            userproblem__problem_correct_answer=True,
            problem__genre='network'
        ).count()

        try:
            network_per = round((solved_network_count / network_count) * 100)

templates/ctf/account_delete.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load static %}

{% block page_title %} BeginnersCTF | アカウント削除{% endblock %}

{% block content %}

<div class="container my-5">
  <!-- タイトル -->
  <h6 class="font-weight-bold text-center grey-text text-uppercase small mb-4">account_delete</h6>
  <h3 class="font-weight-bold text-center white-text pb-2">アカウント削除</h3>
  <hr class="w-header white my-4">

  {% bootstrap_messages %}

  <div class="row d-flex align-items-center justify-content-center">
    <div class="card col-11 col-sm-10 col-md-8 col-lg-4">
      <div class="card-body z-depth-2 px-4">


        <p>アカウントを削除します。この操作は一度実行したら戻せません。よろしいですか？</p>

        <form method="post">
          {% csrf_token %}

          {% bootstrap_form form %}

          {% buttons %}
          <button class="primaryAction btn btn-danger btn-block waves-effect waves-light" type="submit">アカウント削除
          </button>
          {% endbuttons %}
        </form>

      </div>
    </div>
  </div>
</div>
{% endblock %}

templates/ctf/board.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}BeginnersCTF | 掲示板{% endblock %}

{% block content %}
<div class="container my-5">
  <!-- タイトル -->
  <h6 class="font-weight-bold text-center grey-text text-uppercase small mb-4">board</h6>
  <h3 class="font-weight-bold text-center white-text pb-2">掲示板ページ</h3>
  <hr class="w-header white my-4">
</div>
{% endblock %}

templates/ctf/index.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}BeginnersCTF{% endblock %}

{% block content %}
<div class="container my-5">
  <!-- タイトル -->
  <h6 class="font-weight-bold text-center grey-text text-uppercase small mb-4">top</h6>
  <h3 class="font-weight-bold text-center white-text pb-2">トップページ</h3>
  <hr class="w-header white my-4">
</div>
{% endblock %}

templates/ctf/information.html
{% extends "base.html" %}
{% load static %}

{% block page_title %}BeginnersCTF | お知らせ{% endblock %}

{% block content %}
<div class="container my-5">
  <!-- タイトル -->
  <h6 class="font-weight-bold text-center grey-text text-uppercase small mb-4">information</h6>
  <h3 class="font-weight-bold text-center white-text pb-2">お知らせページ</h3>
  <hr class="w-header white my-4">

  {% for information in information_list %}
  <div class="card my-3 p-3 bg-info">
    <h3 class="m-0">{{ information.title }}</h3>
    <hr>
    <p>{{ information.contents }}</p>
    <p class="text-end m-0">{{ information.created_at }}</p>
  </div>
  {% endfor %}

</div>
{% endblock %}

templates/ctf/inquiry.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load static %}

{% block page_title %}BeginnersCTF | お問い合わせ{% endblock %}

{% block content %}
<div class="container my-5">
  <!-- タイトル -->
  <h6 class="font-weight-bold text-center grey-text text-uppercase small mb-4">inquiry</h6>
  <h3 class="font-weight-bold text-center white-text pb-2">お問い合わせページ</h3>
  <hr class="w-header white my-4">

  {% bootstrap_messages %}

  <form method="post" class="">
    {% csrf_token %}

    {% bootstrap_form form %}

    {% buttons %}
    <button class="primaryAction btn btn-primary btn-block waves-effect waves-light w-100 p-4" type="submit">送信
    </button>
    {% endbuttons %}
  </form>

</div>
{% endblock %}

templates/ctf/my_page.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load static %}

{% block page_title %}BeginnersCTF | マイページ{% endblock %}

{% block content %}
<div class="container my-5">
  <!-- タイトル -->
  <h6 class="font-weight-bold text-center grey-text text-uppercase small mb-4">my_page</h6>
  <h3 class="font-weight-bold text-center white-text pb-2">マイページ</h3>
  <hr class="w-header white my-4">

  {% bootstrap_messages %}

  <div class="card p-5">
    <h3 class="mb-5">プロフィール設定</h3>
    <div class="row">

      <div class="col-6">
        <p><img src="{{ user.icon_thumbnail.url }}" class="rounded-circle border me-1" width="300" height="300" alt=""
                loading="lazy">
        </p>
      </div>

      <div class="col-6">
        <h1>{{ user.username }}</h1>
      </div>

    </div>

    <form method="post" class="" enctype="multipart/form-data">
      {% csrf_token %}

      {% bootstrap_form form %}

      {% buttons %}
      <button class="primaryAction btn btn-primary btn-block waves-effect waves-light" type="submit">更新</button>
      {% endbuttons %}

    </form>
  </div>

  <div class="card p-5 mt-5">
    <h3 class="mb-5">アカウントの重要な設定</h3>
    {% buttons %}
    <a href="{% url 'account_change_password' %}">
      <button class="primaryAction btn btn-primary btn-block waves-effect waves-light" type="submit">パスワード変更
      </button>
    </a>
    {% endbuttons %}

    {% buttons %}
    <a href="{% url 'account_email' %}">
      <button class="primaryAction btn btn-primary btn-block waves-effect waves-light" type="submit">メールアドレス変更
      </button>
    </a>
    {% endbuttons %}

    {% buttons %}
    <a href="{% url 'ctf:account_delete' %}">
      <button class="primaryAction btn btn-danger btn-block waves-effect waves-light" type="submit">アカウント削除
      </button>
    </a>
    {% endbuttons %}
  </div>

</div>
{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/removeText.js' %}"></script>
{% endblock %}

templates/ctf/problem_detail.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load static %}

{% block page_title %}BeginnersCTF | 問題詳細{% endblock %}

{% block content %}
<div class="container my-5">
  <!-- タイトル -->
  <h6 class="font-weight-bold text-center grey-text text-uppercase small mb-4">problem_detail</h6>
  <h3 class="font-weight-bold text-center white-text pb-2">問題詳細ページ</h3>
  <hr class="w-header white my-4">

  {% bootstrap_messages %}

  <div class="card p-5 bg-info">
    <h3>{{ problem.name }}</h3>
    <p>{{ problem.statement|safe }}</p>
    <p><a href="../../media/{{ problem.file }}" download>{{ problem.file|cut:"problems/"|default:'' }}</a>
    </p>
  </div>

  <form method="post" class="p-5">
    {% csrf_token %}

    {% bootstrap_form form %}

    {% buttons %}
    <button class="primaryAction btn btn-primary btn-block waves-effect waves-light w-100 p-4" type="submit">解答送信
    </button>
    {% endbuttons %}
  </form>

</div>
{% endblock %}

templates/ctf/problem_list.html
{% extends "base.html" %}
{% load bootstrap5 %}
{% load static %}

{% block page_title %}BeginnersCTF | 問題一覧{% endblock %}

{% block content %}
<div class="container my-5">
  <!-- タイトル -->
  <h6 class="font-weight-bold text-center grey-text text-uppercase small mb-4">problem_list</h6>
  <h3 class="font-weight-bold text-center white-text pb-2">問題一覧ページ</h3>
  <hr class="w-header white my-4">

  {% bootstrap_messages %}

  <div class="search">
    <span class="btn btn-text-size search_item is-active" data-group="">ALL</span>
    <span class="btn btn-text-size search_item" data-group="crypto">Crypto</span>
    <span class="btn btn-text-size search_item" data-group="forensics">Forensics</span>
    <span class="btn btn-text-size search_item" data-group="reversing">Reversing</span>
    <span class="btn btn-text-size search_item" data-group="pwnable">Pwnable</span>
    <span class="btn btn-text-size search_item" data-group="web">Web</span>
    <span class="btn btn-text-size search_item" data-group="network">Network</span>
    <span class="btn btn-text-size search_item" data-group="misc">Misc</span>
  </div>

  <div class="container">
    <div class="row list">
      {% for userproblem in userproblem_list %}
      <div class="col-6 col-md-4 list_item" data-group="{{ userproblem.problem.genre }}">
        <a class="btn card my-3 p-3 bg-info" href="{% url 'ctf:problem_detail' userproblem.problem.pk %}">
          <div class="card-body">
            <h4 class="card-title m-0 btn-text-size">{{ userproblem.problem.name }}</h4>
            <hr class="card-text">
            <p class="card-text btn-text-size">ジャンル：{{ userproblem.problem.genre }}</p>
            <p class="card-text">レベル：{{ userproblem.problem.level }}</p>
            <p class="card-text">点数：{{ userproblem.problem.score }}</p>
            <p class="card-text check-solved">{{ userproblem.problem_correct_answer|yesno:'解答済み☑, 未回答□' }}</p>
          </div>
        </a>
      </div>
      {% endfor %}
    </div>
  </div>

</div>

{% endblock %}

{% block extra_js %}
<script type="text/javascript" src="{% static 'js/filterList.js' %}"></script>
<script type="text/javascript" src="{% static 'js/checkSolved.js' %}"></script>
{% endblock %}

templates/ctf/ranking.html
{% extends "base.html" %}
{% load static %}
{% load django_tables2 %}

{% block page_title %}BeginnersCTF | ランキング{% endblock %}

{% block content %}
<div class="container my-5">
  <!-- タイトル -->
  <h6 class="font-weight-bold text-center grey-text text-uppercase small mb-4">ranking</h6>
  <h3 class="font-weight-bold text-center white-text pb-2">ランキングページ</h3>
  <hr class="w-header white my-4">

  <!-- ウィンドウサイズに合わせて枠の大きさを変える -->
  <div class="container-fluid">
    <!-- 水平方向の横スクロールバーを加える -->
    <div class="table-responsive col-auto">
      <!-- 縞ストライプで見やすくする -->
      <table class="table table-striped">
        {% render_table table %}
      </table>
    </div>
  </div>

</div>
{% endblock %}