ctf/urls.py
from django.urls import path

from . import views

app_name = 'ctf'
urlpatterns = [
    path('', views.index, name="index"),
    path('information/', views.information, name="information"),
    path('ranking/', views.ranking, name="ranking"),
    path('problem_list/', views.problem_list, name="problem_list"),
    path('board/', views.board, name="board"),
    path('inquiry/', views.inquiry, name="inquiry"),
    path('my_page/', views.my_page, name="my_page"),
    path('status/<int:pk>/', views.status, name="status"),
    path('account_delete/', views.account_delete, name="account_delete"),
    path('problem_detail/<int:pk>/', views.problem_detail, name="problem_detail"),
]

templates/base.html
<!doctype html>
{% load bootstrap5 %}
{% bootstrap_css %}
{% bootstrap_javascript %}
{% load static %}
<html lang="ja">

<head>
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <title>{% block page_title %}{% endblock %}</title>

  {# --- css --- #}
  <!-- MDB icon -->
  <link rel="icon" href="img/mdb-favicon.ico" type="image/x-icon"/>
  <!-- Font Awesome -->
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.2/css/all.css"/>
  <!-- Google Fonts Roboto -->
  <link rel="stylesheet" href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;700;900&display=swap"/>
  <!-- MDB -->
  <link rel="stylesheet" href="{% static 'vendor/MDB5-STANDARD-UI-KIT-Free-3.9.0/css/mdb.min.css' %}"/>
  <!-- bootstrap-social-gh-pages -->
  <link rel="stylesheet" href="{% static 'vendor/bootstrap-social-gh-pages/bootstrap-social.css' %}"/>
  <!-- Custom CSS -->
  <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
  {% block extra_css %}{% endblock %}
</head>


<body>
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container-fluid">

    <!-- Navbar brand -->
    <a class="navbar-brand mt-2 mt-lg-0" href="{% url 'ctf:index' %}">BeginnersCTF</a>

    <!-- Toggle button -->
    <button class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <i class="fas fa-bars"></i>
    </button>

    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">

      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ctf:information' %}">お知らせ</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ctf:ranking' %}">ランキング</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ctf:problem_list' %}">問題一覧</a>
        </li>
        <li class="nav-item">
        <!-- <a class="nav-link" href="{% url 'ctf:board' %}">掲示板</a>-->
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'ctf:inquiry' %}">お問い合わせ</a>
        </li>
        <li>
          <hr class="dropdown-divider">
        </li> 
      </ul>
      <!-- Left links -->

      {% if user.is_authenticated %}
      <!-- アイコン -->
      <a class="nav-link dropdown-toggle align-items-center hidden-arrow m-0 px-0" href="#" id="navbarDropdownMenuLink"
         role="button" data-mdb-toggle="dropdown" aria-expanded="false">
        <img src="{{ request.user.icon_thumbnail.url }}" class="rounded-circle border me-1" width="40" height="40" alt=""
             loading="lazy"/>{{ request.user.username }} ( {{ request.user.ranking }}位 - {{ request.user.score }}点 )
        <span class="dropdown-toggle"></span>
      </a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
        <li>
          <a class="dropdown-item" href="{% url 'ctf:my_page' %}">マイページ</a>
        </li>
        <li>
          <a class="dropdown-item" href="{% url 'ctf:status'　user.pk %}">ステータス</a>
        </li>
        <li>
          <a class="dropdown-item" href="{% url 'account_logout' %}">ログアウト</a>
        </li>
      </ul>
      {% else %}
      <!-- ログインボタン -->
      <a class="nav-link px-0" href="{% url 'account_login' %}">ログイン</a>
      {% endif %}
    </div>
    <!-- Collapsible wrapper -->


  </div>
  <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</nav>
<!-- Navbar -->

{% block content %}{% endblock %}

{# --- js --- #}
<!-- MDB -->
<script type="text/javascript" src="{% static 'vendor/MDB5-STANDARD-UI-KIT-Free-3.9.0/js/mdb.min.js' %}"></script>
<!-- JQuery -->
<script type="text/javascript" src="{% static 'js/jquery-3.6.0.min.js' %}"></script>
<!-- Custom scripts -->
{% block extra_js %}{% endblock %}
</body>

</html>